version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/pywry"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/pywry/docs"
    schedule:
      interval: "weekly"
