"""ACP-native Chat component for PyWry.

This subpackage provides the complete chat system: data models, session
primitives, typed update notifications, artifact renderers, provider
adapters, RBAC integration, and the ``ChatManager`` orchestrator.

All public symbols are re-exported here for convenience::

    from pywry.chat import ChatManager, ChatMessage, ContentBlock
    from pywry.chat.models import TextPart, ACPToolCall
    from pywry.chat.providers import ChatProvider, get_provider
"""

from __future__ import annotations

from .artifacts import (
    AppArtifact,
    Artifact,
    CodeArtifact,
    HtmlArtifact,
    ImageArtifact,
    JsonArtifact,
    MarkdownArtifact,
    PlotlyArtifact,
    TableArtifact,
    TradingViewArtifact,
    TradingViewSeries,
    _ArtifactBase,
)
from .html import build_chat_html
from .models import (
    EVENT_QUEUE_MAX_SIZE,
    GENERATION_HANDLE_TTL,
    MAX_CODE_BLOCK_LINES,
    MAX_CONTENT_LENGTH,
    MAX_MESSAGE_SIZE,
    MAX_MESSAGES_PER_THREAD,
    MAX_RENDERED_MESSAGES,
    MAX_THREADS_PER_WIDGET,
    SEND_COOLDOWN_MS,
    STREAM_TIMEOUT_SECONDS,
    TASK_REAPER_INTERVAL,
    ACPCommand,
    ACPCommandInput,
    ACPToolCall,
    AudioPart,
    ChatConfig,
    ChatMessage,
    ChatTaskState,
    ChatThread,
    ChatWidgetConfig,
    ContentBlock,
    EmbeddedResource,
    EmbeddedResourcePart,
    GenerationCancelledError,
    GenerationHandle,
    ImagePart,
    ResourceLinkPart,
    TextPart,
    ToolCallKind,
    ToolCallLocation,
    ToolCallStatus,
)
from .permissions import ACP_PERMISSION_MAP, check_acp_permission
from .providers import ChatProvider, get_provider
from .session import (
    AgentCapabilities,
    AgentInfo,
    ClientCapabilities,
    ConfigOptionChoice,
    PermissionOption,
    PermissionOutcome,
    PermissionRequest,
    PlanEntry,
    PromptCapabilities,
    SessionConfigOption,
    SessionMode,
    StopReason,
)
from .updates import (
    AgentMessageUpdate,
    ArtifactUpdate,
    CitationUpdate,
    CommandsUpdate,
    ConfigOptionUpdate,
    ModeUpdate,
    PermissionRequestUpdate,
    PlanUpdate,
    SessionUpdate,
    StatusUpdate,
    ThinkingUpdate,
    ToolCallUpdate,
)


__all__ = [
    "ACP_PERMISSION_MAP",
    "EVENT_QUEUE_MAX_SIZE",
    "GENERATION_HANDLE_TTL",
    "MAX_CODE_BLOCK_LINES",
    "MAX_CONTENT_LENGTH",
    "MAX_MESSAGES_PER_THREAD",
    "MAX_MESSAGE_SIZE",
    "MAX_RENDERED_MESSAGES",
    "MAX_THREADS_PER_WIDGET",
    "SEND_COOLDOWN_MS",
    "STREAM_TIMEOUT_SECONDS",
    "TASK_REAPER_INTERVAL",
    "ACPCommand",
    "ACPCommandInput",
    "ACPToolCall",
    "AgentCapabilities",
    "AgentInfo",
    "AgentMessageUpdate",
    "AppArtifact",
    "Artifact",
    "ArtifactUpdate",
    "AudioPart",
    "ChatConfig",
    "ChatMessage",
    "ChatProvider",
    "ChatTaskState",
    "ChatThread",
    "ChatWidgetConfig",
    "CitationUpdate",
    "ClientCapabilities",
    "CodeArtifact",
    "CommandsUpdate",
    "ConfigOptionChoice",
    "ConfigOptionUpdate",
    "ContentBlock",
    "EmbeddedResource",
    "EmbeddedResourcePart",
    "GenerationCancelledError",
    "GenerationHandle",
    "HtmlArtifact",
    "ImageArtifact",
    "JsonArtifact",
    "MarkdownArtifact",
    "ModeUpdate",
    "PermissionOption",
    "PermissionOutcome",
    "PermissionRequest",
    "PermissionRequestUpdate",
    "PlanEntry",
    "PlanUpdate",
    "PlotlyArtifact",
    "PromptCapabilities",
    "ResourceLinkPart",
    "SessionConfigOption",
    "SessionMode",
    "SessionUpdate",
    "StatusUpdate",
    "StopReason",
    "TableArtifact",
    "TextPart",
    "ThinkingUpdate",
    "ToolCallKind",
    "ToolCallLocation",
    "ToolCallStatus",
    "ToolCallUpdate",
    "TradingViewArtifact",
    "TradingViewSeries",
    "_ArtifactBase",
    "build_chat_html",
    "check_acp_permission",
    "get_provider",
]
