"""PyWry - Lightweight Python window manager using PyTauri.

This package provides a simple API for displaying HTML content in native
windows with support for Plotly.js, AG Grid, and custom event handling.
"""

# Frozen-executable subprocess interception — runs before any other
# pywry import.  In a frozen distributable (PyInstaller / Nuitka / cx_Freeze),
# when the parent process spawns itself as the Tauri subprocess, this call
# enters the Tauri event loop and exits immediately so the developer's
# application code never runs a second time.  It is a complete no-op in
# every other situation (normal Python, frozen parent process, etc.).
from ._freeze import freeze_support, setup_pytauri_runtime


freeze_support()
setup_pytauri_runtime()

# Inline notebook module - import functions directly
from . import inline
from .app import PyWry
from .asset_loader import AssetLoader, get_asset_loader
from .callbacks import CallbackFunc, WidgetType, get_registry
from .chat import (
    AppArtifact,
    ChatProvider,
    CodeArtifact,
    HtmlArtifact,
    ImageArtifact,
    JsonArtifact,
    MarkdownArtifact,
    PlotlyArtifact,
    TableArtifact,
    TradingViewArtifact,
    TradingViewSeries,
    build_chat_html,
    get_provider,
)
from .chat.manager import (
    ChatContext,
    ChatManager,
    SettingsItem,
)
from .chat.models import (
    ACPCommand,
    ACPToolCall,
    ChatConfig,
    ChatMessage,
    ChatThread,
    ContentBlock,
)
from .chat.session import (
    PlanEntry,
    SessionConfigOption,
    SessionMode,
)
from .chat.updates import (
    AgentMessageUpdate,
    ArtifactUpdate,
    CitationUpdate,
    CommandsUpdate,
    ConfigOptionUpdate,
    ModeUpdate,
    PlanUpdate,
    StatusUpdate,
    ThinkingUpdate,
    ToolCallUpdate,
)
from .config import (
    AssetSettings,
    HotReloadSettings,
    LogSettings,
    PyWrySettings,
    SecuritySettings,
    ThemeSettings,
    TimeoutSettings,
    WindowSettings,
)
from .grid import (
    ColDef,
    ColGroupDef,
    DefaultColDef,
    GridOptions,
    RowSelection,
    build_grid_config,
    to_js_grid_config,
)
from .hot_reload import HotReloadManager
from .inline import block, show_dataframe, show_plotly, show_tvchart
from .menu_proxy import MenuProxy
from .modal import Modal
from .models import (
    HtmlContent,
    ThemeMode,
    WindowConfig,
    WindowMode,
)
from .notebook import (
    NotebookEnvironment,
    detect_notebook_environment,
    is_anywidget_available,
    should_use_inline_rendering,
)
from .plotly_config import (
    ModeBarButton,
    ModeBarConfig,
    PlotlyConfig,
    PlotlyIconName,
    StandardButton,
    SvgIcon,
)
from .state_mixins import (
    GridStateMixin,
    PlotlyStateMixin,
    ToolbarStateMixin,
)
from .toolbar import (
    Button,
    Checkbox,
    DateInput,
    Div,
    Marquee,
    MultiSelect,
    NumberInput,
    Option,
    RadioGroup,
    RangeInput,
    SearchInput,
    SecretInput,
    Select,
    SliderInput,
    TabGroup,
    TextArea,
    TextInput,
    TickerItem,
    Toggle,
    Toolbar,
    ToolbarItem,
)
from .tray_proxy import TrayProxy
from .tvchart import (
    DatafeedProvider,
    QuoteData,
    TVChartBar,
    TVChartConfig,
    TVChartData,
    TVChartDatafeedBarUpdate,
    TVChartDatafeedConfigRequest,
    TVChartDatafeedConfigResponse,
    TVChartDatafeedConfiguration,
    TVChartDatafeedHistoryRequest,
    TVChartDatafeedHistoryResponse,
    TVChartDatafeedMarksRequest,
    TVChartDatafeedMarksResponse,
    TVChartDatafeedResolveRequest,
    TVChartDatafeedResolveResponse,
    TVChartDatafeedSearchRequest,
    TVChartDatafeedSearchResponse,
    TVChartDatafeedServerTimeRequest,
    TVChartDatafeedServerTimeResponse,
    TVChartDatafeedSubscribeRequest,
    TVChartDatafeedSymbolType,
    TVChartDatafeedTimescaleMarksRequest,
    TVChartDatafeedTimescaleMarksResponse,
    TVChartDatafeedUnsubscribeRequest,
    TVChartExchange,
    TVChartLibrarySubsessionInfo,
    TVChartMark,
    TVChartSearchSymbolResultItem,
    TVChartStateMixin,
    TVChartSymbolInfo,
    TVChartSymbolInfoPriceSource,
    TVChartTimescaleMark,
    UDFAdapter,
    build_tvchart_toolbars,
)
from .types import (
    CheckMenuItemConfig,
    IconMenuItemConfig,
    MenuConfig,
    MenuItemConfig,
    MouseButton,
    MouseButtonState,
    PredefinedMenuItemConfig,
    PredefinedMenuItemKind,
    SubmenuConfig,
    TrayIconConfig,
)
from .widget import PyWryAgGridWidget, PyWryPlotlyWidget, PyWryTVChartWidget, PyWryWidget
from .window_manager import BrowserMode, get_lifecycle


__version__ = "2.0.0"

__all__ = [
    "ACPCommand",
    "ACPToolCall",
    "AgentMessageUpdate",
    "AppArtifact",
    "ArtifactUpdate",
    "AssetLoader",
    "AssetSettings",
    "BrowserMode",
    "Button",
    "CallbackFunc",
    "ChatConfig",
    "ChatContext",
    "ChatManager",
    "ChatMessage",
    "ChatProvider",
    "ChatThread",
    "CheckMenuItemConfig",
    "Checkbox",
    "CitationUpdate",
    "CodeArtifact",
    "ColDef",
    "ColGroupDef",
    "CommandsUpdate",
    "ConfigOptionUpdate",
    "ContentBlock",
    "DatafeedProvider",
    "DateInput",
    "DefaultColDef",
    "Div",
    "GridOptions",
    "GridStateMixin",
    "HotReloadManager",
    "HotReloadSettings",
    "HtmlArtifact",
    "HtmlContent",
    "IconMenuItemConfig",
    "ImageArtifact",
    "JsonArtifact",
    "LogSettings",
    "MarkdownArtifact",
    "Marquee",
    "MenuConfig",
    "MenuItemConfig",
    "MenuProxy",
    "Modal",
    "ModeBarButton",
    "ModeBarConfig",
    "ModeUpdate",
    "MouseButton",
    "MouseButtonState",
    "MultiSelect",
    "NotebookEnvironment",
    "NumberInput",
    "Option",
    "PlanEntry",
    "PlanUpdate",
    "PlotlyArtifact",
    "PlotlyConfig",
    "PlotlyIconName",
    "PlotlyStateMixin",
    "PredefinedMenuItemConfig",
    "PredefinedMenuItemKind",
    "PyWry",
    "PyWryAgGridWidget",
    "PyWryPlotlyWidget",
    "PyWrySettings",
    "PyWryTVChartWidget",
    "PyWryWidget",
    "QuoteData",
    "RadioGroup",
    "RangeInput",
    "RowSelection",
    "SearchInput",
    "SecretInput",
    "SecuritySettings",
    "Select",
    "SessionConfigOption",
    "SessionMode",
    "SettingsItem",
    "SliderInput",
    "StandardButton",
    "StatusUpdate",
    "SubmenuConfig",
    "SvgIcon",
    "TVChartBar",
    "TVChartConfig",
    "TVChartData",
    "TVChartDatafeedBarUpdate",
    "TVChartDatafeedConfigRequest",
    "TVChartDatafeedConfigResponse",
    "TVChartDatafeedConfiguration",
    "TVChartDatafeedHistoryRequest",
    "TVChartDatafeedHistoryResponse",
    "TVChartDatafeedMarksRequest",
    "TVChartDatafeedMarksResponse",
    "TVChartDatafeedResolveRequest",
    "TVChartDatafeedResolveResponse",
    "TVChartDatafeedSearchRequest",
    "TVChartDatafeedSearchResponse",
    "TVChartDatafeedServerTimeRequest",
    "TVChartDatafeedServerTimeResponse",
    "TVChartDatafeedSubscribeRequest",
    "TVChartDatafeedSymbolType",
    "TVChartDatafeedTimescaleMarksRequest",
    "TVChartDatafeedTimescaleMarksResponse",
    "TVChartDatafeedUnsubscribeRequest",
    "TVChartExchange",
    "TVChartLibrarySubsessionInfo",
    "TVChartMark",
    "TVChartSearchSymbolResultItem",
    "TVChartStateMixin",
    "TVChartSymbolInfo",
    "TVChartSymbolInfoPriceSource",
    "TVChartTimescaleMark",
    "TabGroup",
    "TableArtifact",
    "TextArea",
    "TextInput",
    "ThemeMode",
    "ThemeSettings",
    "ThinkingUpdate",
    "TickerItem",
    "TimeoutSettings",
    "Toggle",
    "ToolCallUpdate",
    "Toolbar",
    "ToolbarItem",
    "ToolbarStateMixin",
    "TradingViewArtifact",
    "TradingViewSeries",
    "TrayIconConfig",
    "TrayProxy",
    "UDFAdapter",
    "WidgetType",
    "WindowConfig",
    "WindowMode",
    "WindowSettings",
    "__version__",
    "block",
    "build_chat_html",
    "build_grid_config",
    "build_tvchart_toolbars",
    "detect_notebook_environment",
    "freeze_support",
    "get_asset_loader",
    "get_lifecycle",
    "get_provider",
    "get_registry",
    "inline",
    "is_anywidget_available",
    "should_use_inline_rendering",
    "show_dataframe",
    "show_plotly",
    "show_tvchart",
    "to_js_grid_config",
]
